### ISSUE TITLE
Alt + enter pc crash

### ISSUE THREAD

**Issue by Immersive7** [bolrog/d2dx#109]
When I try to go full screen my PC just shuts down or shows the :( icon while collecting data

**Comment by MAXBURAOT** [comment]
> When I try to go full screen my PC just shuts down or shows the :( icon while collecting data

reinstall your diablo what version are u using

**Comment by updawg** [comment]
You are the only one reporting this type of issue since this has been
released. I would first rule out that it isn't an issue with the operating
system.

I would do the common fixes from an administrative command prompt:

sfc /scannow
dism /online /cleanup-image /restorehealth

Use Direct Drive Uninstaller in safe mode to remove your video drive. Then
install the latest version of the video drive.

**Comment by bolrog** [comment]
It sounds to me like a driver problem or a hardware issue. D2DX does fullscreen mode by expanding the window to cover the screen, so it's not really different than the window mode.

**Comment by Immersive7** [comment]
Yeah my laptop is dying, I can play normally i just have to put -w or not depends on how i want to play
