### ISSUE TITLE
Request: Change command line arguments to an ini file.

### ISSUE THREAD

**Issue by updawg** [bolrog/d2dx#25]
Would it make more sense to have an ini file with the various options as opposed to tacking them on to a command line argument? With all the additional features you've added it seems like it makes sense.

However, this is just an idea, I am very grateful for your work!

**Comment by bolrog** [comment]
Thanks for the suggestion!

The guiding principle I use is that every feature/option that I add to D2DX should be sensible and on by default. 

For example, I'm doing quite a bit of tuning work on e.g. the AA to ensure that it doesn't alter the in-game graphics in areas where it shouldn't (only really on the edges where D2 shows jaggies, which is due to technical limitations of the tech they used back then).

The cmdline options are more meant for users who either run into trouble with some feature, or for some reason really don't like one or more of them. For that reason the command line options are all "subtractive" and named "-dxnoX".

I think if I added a .ini file, it would be somewhat of a failure of the ambition for D2DX to be "configurationless" and have good defaults out of the box.

With that said, I've only guessed as to what features players would like/not like, so I'm always open for discussion regarding that! Are there any options in particular that you don't like having enabled? What would you like to configure?

**Comment by updawg** [comment]
Understood. Diablo is a game I like to come back to yearly, and I now use
this (previously the IamTrial in conjunction with Sven's glide wrapper),
Basemod by Devurandom, BH from SlashDiablo, and Plugy. I keep these files
in a mods folder and drop them in on a fresh 1.13c install. Since the rest
of these mods had ini files I figured having it in a set-it and forget
type configuration is good for longevity. I have a gysnc monitor and don't
like the DX logo so my command line arguments were getting pretty long.

Regardless, I look forward to future updates! I follow this on github and
get excited any time an alert comes through that this has been updated.

**Comment by bolrog** [comment]
Thanks for explaining your point of view, I understand where you're coming from! I'll add support for a simple ini file soon.

**Comment by bolrog** [comment]
Added in release 419. Just put a text file named "d2dx.cfg" in the D2 folder and add the cmdline arguments in there (still need to say -3dfx on the actual command line).

**Comment by updawg** [comment]
Awesome! That was a quick turnaround. I can't wait to test it later. Thanks again!

**Comment by pairofdocs** [comment]
👍  for the config file

I also like the ini/config file idea since it's just easier to edit for me. And I do a lot of fiddling with my settings for games and mods.

My personal preferences are `novsync`, `noaa`, `no wide screen` 😄 and the faster + prettier the game runs the better

For d2 players that are 'modders' the config file is great
