### ISSUE TITLE
XP compat mode/mods

### ISSUE THREAD

**Issue by bolrog** [bolrog/d2dx#26]
Investigate ways of staying compatible with mods that require being run as admin or xp compat mode.

**Comment by IAmTrial** [comment]
In terms of staying compatible with XP, you will likely have to use the deprecated VS 2017 build tools for Windows XP, which may not be supported once VS 2022 releases. I have observed that these build tools are not really a perfect solution to the issue, as DLLs would not properly load under certain circumstances.

One potential fix is to convert the project files to VS 2010, which is the latest one to properly support Windows XP without any strange issues. The problem is that this approach requires the conversion of C++11 to C++98 code. Some features of C++11 that are supported can be observed in the chart at [cppreference](https://en.cppreference.com/w/cpp/11#Compiler_support).

Otherwise, you could try Visual C++ 6.0 if you want to support to go as far back as Windows 95. Be warned that the C++ compliance for C++98 is incomplete and can may have bugs. C89 compiles without issue (with the exception of Microsoft's implementation of sprintf and wsprintf %s and %ls which is carried over to new compilers).

**Comment by CaiMiao** [comment]
D2SE requires winxp (or at least win7) compact mode on win8+ to run the game.

I think you can disable some "problematic" feature when such mode is detected, as temp workaround?

**Comment by bolrog** [comment]
You can now use -dxnocompatmodefix to bypass the check in D2DX. Hopefully that solves the issue for this mod.

**Comment by bolrog** [comment]
@IAmTrial thanks! The issue is rather the reverse - using the XP compatibility mode when running the game in e.g. Windows 10. D2DX prefers that this isn't used, but I've learned it's required for various other mods.
