### ISSUE TITLE
Walking into a Town Portal to any part of Act 3 often causes a crash (MoP related 0.99.504)

### ISSUE THREAD

**Issue by loktari** [bolrog/d2dx#49]
Happens while playing in full screen. Have not tested windowed mode. Disabling MoP stopped the crashes.

Act 1 and 2 were fine, did not test Act 4 and 5 as I disabled MoP to be able to play through acts 3 to 5 normal. 

Using teleport sometimes also causes glitches for less than a second or until the character starts to move.

**Comment by bolrog** [comment]
See if release 505b (just released) helps!

**Comment by loktari** [comment]
Not fixed. Started happening in act 1 now.

**Comment by bolrog** [comment]
Which part of the issue? The fix only affected occasional bad positioning of the character after teleporting. I'm still looking for the crash.

**Comment by loktari** [comment]
The crash is not fixed.

**Comment by bolrog** [comment]
Right.

**Comment by rob151515** [comment]
I'm also experiencing a crash when entering town portals. I'm seeing this in Act 1. Seems to be happening quite frequently for me but I'm not able to nail down a set of steps to reproduce it 100% of the time...

I'm using version 0.99.505b and 1.14d of Diablo II. Removing the '-dxtestmop' flag seems to fix the problem for me also. At least I haven't seen any crashes since turning it off. Hopefully this can be fixed - it's quite jarring to go back to not using this mod now!

**Comment by bolrog** [comment]
I have a fix coming up, I hope.

**Comment by loktari** [comment]
We hope, your tool is extremely nice, makes the game a lot more enjoyable. I'm curious about what still motivates people to develop and expand tools like this. Good stuff!

**Comment by bolrog** [comment]
Thanks! I basically picked up the game earlier this year (played it when it came out), and for fun I decided to try overcoming the limitations of the game because they annoyed me (glitches in Windows 10, low stuttering fps, no widescreen support etc). I'm very glad that I found Mir Drualgas D2HD mod so that I could add custom resolution/widescreen support, and now that I finally came up with a way to solve the low fps I think it's getting close to the vision I had. So yeah, it's a side project that went a bit overboard. 😁 

I think I may have found the issue causing the crashes, see release 506. I played a while and tried TP'ing back and forth and didn't get it to crash, at least.

**Comment by loktari** [comment]
I'll try it later when I get the time. I played it when it came out too :) Good stuff!

**Comment by loktari** [comment]
Seems to be fixed, the only issue I can see now is the item labels jittering when my character is moving while pressing ALT.

**Comment by rob151515** [comment]
Yeah just spent 10 minutes going through portals and no crash to speak of so I think this one is fixed. I can no go back to enabling this mod. Thank you!
