### ISSUE TITLE
Old Medianxl can do 1280x720 but the new version cannot

### ISSUE THREAD

**Issue by Silvist** [bolrog/d2dx#54]
First off my apologies for posting this here, wasn't sure where to post suggestions on github, still new to using it :D

So before anything else, thank you so much for your hard work on this!  Its really amazing, even compared to other resolution tweaks I've used in the past.  Resizing doesn't glitch out, and is very seemless.

![image](https://user-images.githubusercontent.com/950703/117549119-76318980-afed-11eb-92ea-b8a656429690.png)

I was able to use your mod on an older version of medianxl to use 1280x720, but not able to do the same on the newest one.

![image](https://user-images.githubusercontent.com/950703/117549153-92cdc180-afed-11eb-8de2-02c7999a2808.png)

Is there a reason you've imposed this restriction on the new one or is this imposed by the Median devs?  I keep seeing people "claim" that the new version cannot do the higher res, but that makes no sense if the old one can.  I'm not even sure where the resolution restriction is located in the files (unless its a modified exe).  

If the issue is the "newer" textures dc6, it would be a simple fix to just run a script to resize all of the modded textures.  I would even be willing to do this myself, if this is the reason the authors "gimp" themselves into lower resolutions lol.

I'm guessing that the issue is multiplayer, pvp, and monster AI.  Which honestly has always been a flaw with the d2 engine at its core.

**Comment by bolrog** [comment]
Thank you, I'm glad you like it!

I am using the D2HD mod by Mir Drualga to set resolutions btw, but it's a little customized.

It's true that I have a special check for Median XL Sigma. I think my reasoning was to allow the default 1024x768 res. I didn't check for older versions of MXL since it seemed unnecessary.

I should probably remove the check altogether.. I'll do that for the next release!

**Comment by Silvist** [comment]
Thanks @bolrog I'd appreciate that!  

What I meant earlier was, I searched high and low for where the resolution restrictions were, even inside of my registry.  I did find the Glide3toopenGL registry entry, and diablo 2 for resolution, but nothing from Medianxl.

I would be happy to test if this works or not for Medianxl prior to you commiting it to your main build.

Once again thank you for your hard work! Its amazing being able to play a 90s game with some quality of life fixes in this day and age :D

**Comment by Pear1st** [comment]
Where can I find D2HD mod by Mir Drualga？Please... @bolrog

**Comment by bolrog** [comment]
I've published release 510 where the restriction for MedianXL has been removed, and you can set the game size in d2dx.cfg.

@Pear1st the separate version of D2HD doesn't work, but D2DX has it built in anyway.

**Comment by IAmTrial** [comment]
When I originally wrote D2HD, the original goal was to expand the ingame resolutions available for the communities I had in mind. Those two communities being SlashDiablo and its sister community D2Resurgence. The use of D2HD on other servers has made me realize that there needed to be a system to prevent use of my work on other servers that do not authorize the use of D2HD.

As you can tell, Median XL's authors already have their own solution for what kind of resolution that they would want to balance their mod around. To override Median XL's resolution code could mean much more work involved to not break the existing resolution patches applied by Median XL's code. At any point, the Median XL developers could make a change that could break everything. And since this is the way the developers intended for Median XL to be played, I think that to implement D2HD compatibility would go against the mod authors' wishes.

**Comment by bolrog** [comment]
You bring a good point, @IAmTrial. I don't want to step on the toes of server owners... and perhaps the "motion prediction" high-fps feature I've added is also such a feature that should be cleared with those, because it seems like it could be abused for advantage.

**Comment by Silvist** [comment]
@bolrog Alright, thanks for trying.  All I wanted to do was play at aspect 16:9 instead of being forced to play at 4:3 for their mod lol.  Doing the fix to stretch my resolution isn't my cup of tea with a game from the 90s.
