### ISSUE TITLE
The solution of more games

### ISSUE THREAD

**Issue by chenxiuandroid** [bolrog/d2dx#58]
Hello, d2dx is really a very powerful project. I applied it in my mod and thought it was very cool. However, once I use d2dx, there will be only one game, and I can't open more than one. Is there any plan to repair it in the future?

**Comment by IAmTrial** [comment]
It is in my opinion that D2DX should remain mainly focused on being a graphics wrapper for Glide mode in Diablo 2. Adding additional features like this seems to be outside the scope of what this project should do and can quite easily render it incompatible with mods that provides the same feature you mentioned.

**Comment by CaiMiao** [comment]
it seems you misinterpreted his meaning due to his broken english.

he just want multiple game instance with d2dx

**Comment by IAmTrial** [comment]
> it seems you misinterpreted his meaning due to his broken english.
> 
> he just want multiple game instance with d2dx

There was no misunderstanding from me, I already understood what @chenxiuandroid wanted when they wrote

> ...there will be only one game, and I can't open more than one.

Multiple game instances is trivial to implement (basically a 1 byte patch), but the addition is effectively feature creep for something that originally began as a Glide wrapper and has now expanded to graphical enhancements. While it may be convenient for the vanilla end-user, it is not so much for mods that implement their own incompatible patch mechanisms or perform integrity checks and assertions. In terms of engineering, this would mean having to maintain a solution that works for every version that this wrapper is willing to support. This delays releases for new versions on features that not everyone would expect, since the features are unrelated to the software's role as a Glide wrapper. Once a feature is added, it becomes very hard to remove, since even the smallest unknown percentage of users will continue to rely on such a feature. Also, not every mod or community is willing to permit multiboxing. Once this feature is added, there will need to be additional work done to ensure that the feature is not used in places where it isn't allowed.

A command line switch is a workaround to the issue, but the problem of end-user misapplication then comes into play. If 'off' is the default behavior, then it may exist as a feature that not many are aware of. Not many people are willing to read manuals, and some can't read manuals because of language barriers. If 'on' is the default behavior, then it affect people's Diablo II install in an "unexpected" way.

If you actually want to use multiboxing solutions, it should exist as a separate repository, such as [SGD2FreeMultibox](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Multibox).

**Comment by updawg** [comment]
Mir,

I love your work and everything you've contributed to the Diablo community.
It has bettered this game forever.

But the points you are raising are conclusions you came to yourself.

If you came to this conclusion earlier we may not have motion prediction,
true borderless windows, customizable window placement, among others, as
you may have deemed them outside the scope of this project.

I understand your concerns about certain aspects conflicting with certain
mod creators, but I don't think that is reason to restrict innovation. The
code is out there, and anyone with the knowhow can remove the restrictions.

The points about hiding settings in config files is true in the majority of
software, but something only available via GitHub for a 20 year old game
has a completely different audience. Additionally free software comes with
no expected support or warranty. Anyone with these expectations can be
ignored.

I don't expect eastern sun mod to work with Basemod, but if it does that is
a perk. There is no expectation for Bolrog to continue support this project
even tomorrow, but everything he/she does is a benefit for Diablo fans
forever.

**Comment by IAmTrial** [comment]
I have misspoke, with this line:

> This delays releases for new versions on features that not everyone would expect, since the features are unrelated to the software's role as a **Glide wrapper.**

While I did say that this was a Glide wrapper, I think I should clarify what I mean by that. This is an excellent project, and I think that many of the features being implemented by the author are no short of amazing. When I call it a Glide wrapper, I mean in terms of how it installs into Diablo II.

What I am actually trying to comment on are very specific issues that are best left in a "won't fix" state. I've explored the problem of Median XL not working with D2HD, though with a version of the mod prior to Sigma. And I can already say that the patches applied by Median XL **really do not allow people to blindly tamper with the mod**. And I think that this has to be respected. The Median XL code makes certain checks that are intended to interfere with the functionality of custom resolution mods. My advice to the author was to avoid custom resolution work on Median XL because they would ultimately come to the same conclusion as me. The Glide wrapping capabilities are perfectly fine to explore with Median XL. As for any other mod that doesn't intentionally interfere with resolution mods, I don't object to compatibility. I even go out of my way to make sure that there is PlugY compatibility in SGD2FreeRes, because PlugY doesn't proactively interfere with SGD2FreeRes's functionality.

> If you came to this conclusion earlier we may not have motion prediction,
true borderless windows, customizable window placement, among others, as
you may have deemed them outside the scope of this project.
>
>  I understand your concerns about certain aspects conflicting with certain
mod creators, but I don't think that is reason to restrict innovation. The
code is out there, and anyone with the knowhow can remove the restrictions.

I actually do not have any objections to the author adding custom features to the Glide wrapper that enable special rendering effects or graphical features. These are completely in line with the graphics nature of the software. These are features that I think make most sense to be implemented by a Glide wrapper. I leave feedback on particular issues or pull requests when I feel that there is something important to say. It is good to see that the repository has been gaining more attention, and I think this project has great potential.

However, this particular issue to enable multiple instances, or multiboxing, is completely unrelated to the purpose of a Glide wrapper. The first problem is that it requires a patch to the game's code. Most, if not all, of the best features that are available in D2DX are implemented entirely through its behavior as a Glide wrapper. These features do not require a patch to the game code. The custom resolution solution is also soft-integrated into the code, and exists in an entirely separate repository. So the custom resolution is at least acceptable, because it is related to graphics and is not hard-integrated into the codebase. The second problem is that multiboxing has nothing at all to do with graphics. This is what I mean by feature creep. Unrelated features should have a distinct separation of code, so it becomes obvious the purpose of the code and the purpose of the software.

I wanted to demonstrate that the problem of multiboxing has nothing to do with how difficult it is to implement. It has more to do with the long-term maintenance of the added code and the affected compatibility with other mods.

> The points about hiding settings in config files is true in the majority of
software, but something only available via GitHub for a 20 year old game
has a completely different audience. Additionally free software comes with
no expected support or warranty. Anyone with these expectations can be
ignored.

I don't disagree with the idea that settings can be added to enable or disable features. The only problem is when user error results in issues being unnecessarily made. If the author is willing, the issue takes effort to resolve, and will pop up from time to time. The valid bug reports still need to be sorted among the "won't fix" reports. Simply not having a particular feature prevents user error issues related to the feature from popping up. And again, I don't think that adding features is the problem. It is adding features that don't fit the intended established goals of D2DX.

**Comment by bolrog** [comment]
Good discussion here! I will say that I largely agree with Mir, and the rule of thumb for me when considering features is pretty much what has been stated. If it relates to graphical enhancement or the behavior of the game window in relation to the OS, it's a likely fit for D2DX. At the same time I don't want to stray too far from the original look and feel of the game. The slight AA, widescreen and high fps that's in right now is toeing that line - and intentionally so, because it was my original vision. I'm not sure how much further I'll take it.

For multiboxing it's more complicated, as elaborated above, and I would only go as far as making sure D2DX works well within other projects, e.g. a tabbed multiwindow launcher, if such a thing exists.

As for configurability, I have somewhat altered my principle of just having sensible defaults with some opt-out flags, by adding a few more "open" options like custom resolution and tweaks to the window behavior. I don't want to make it TOO open ended as that turns into a maintainability nightmare, but so far it's fine.

**Comment by updawg** [comment]
Mir,

Thanks for taking time to respond to each one of my points. I agree after
reading your positions and intent that it makes sense from a
developer's perspective how a project should have a defined scope. In this
instance, anything outside of using it as a drop in glide replacement would
indicate that it is better suited for another project.

Increasing the scope, increases complexity, which makes maintainability a
nightmare.

I think myself, like others who have been commenting, are enjoying each new
release with new features to a game we love. I appreciate you and Bolrog
for the continued support and life you breathe into this game. I think most
of the feature requests (myself included - tabbed support) came from the
ReadMe page where it sought out requests. I took this as an opportunity to
see if Bolrog was interested in implementing such a feature.

Additionally, I also wanted to thank Mir because way back when I asked if
he could support his Diablo HD implementation with glide, when it initially
only supported DirectDraw, and somehow he figured it out. So thank you Mir!

**Comment by CaiMiao** [comment]
Now I may realized what he wanted to ask...

By any chance he was using D2Loader to create game instance,  
but D2Loader won't open second instance with D2DX.
