### ISSUE TITLE
[Feature Request]Fully handle all SGD2FreeRes configuration in d2dx cfg

### ISSUE THREAD

**Issue by tytannial** [bolrog/d2dx#93]
The built-in sgd2freeres configuration can't be change and some of the options are missing.

**Comment by bolrog** [comment]
For the built-in version of sgd2freeres, I want it to be a simple in-box way to get custom resolutions. By design, D2DX will emit a config that is known to work.

So my recommendation in your scenario is to use -dxnoresmod and load sgd2freeres as a stand-alone mod instead. Then you "own" the config file.

**Comment by tytannial** [comment]
Right! I forget d2dx is glide wrapper.
